name: deployment

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Run Pint
        run: vendor/bin/pint

      - name: Format Frontend
        run: npm run format

      - name: Lint Frontend
        run: npm run lint

      - name: Run Build
        run: npm run build
      # Prepare build files (optional: customize this step)
      - name: Prepare Build Files
        run: |
          mkdir -p build
          cp -r public/* build/  # Copy public directory (including compiled React assets)
          cp -r app build/       # Copy app directory (if needed)
          cp -r bootstrap build/ # Copy bootstrap directory
          cp -r config build/    # Copy config directory
          cp -r database build/  # Copy database directory (for migrations)
          cp -r routes build/    # Copy routes directory
          cp -r resources build/ # Copy resources directory (if needed)
          cp -r vendor build/    # Copy vendor directory (Composer dependencies)
          cp artisan build/      # Copy artisan file
      # Deploy to Hostinger via SSH (uncomment FTP section below if using FTP)
      # # Copy build files to Hostinger via SSH
      - name: Deploy to Hostinger via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: 'build/*' # Source files to copy
          target: ${{ secrets.HOSTINGER_PATH }} # Destination on Hostinger
          strip_components: 1 # Removes the 'build/' prefix when copying
          overwrite: true # Overwrite existing files
      # - name: Deploy to Hostinger via SSH
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       cd ${{ secrets.HOSTINGER_PATH }}
      #       git pull origin main  # Assumes Git is set up on Hostinger
      #       composer install --no-dev --optimize-autoloader --no-interaction
      #       php artisan migrate --force  # Run migrations (optional)
      #       php artisan config:cache
      #       php artisan route:cache
      #       php artisan view:cache
